# --------------------------------------------------------------
# Ce fichier contient tous les paramètres modifiables du module.
# ! Ne pas modifier les noms de variables !
# ! Ne pas utiliser les caractères " et ' qui sont réservés pour la délimitation des clés dans les dictionnaires Python !
# Les valeurs peuvent être mdifiées selon les préférences.
# Les indentations doivent être respectées strictement.
# --------------------------------------------------------------

# Paramètres réseau
network :
  server :
    host : localhost # L'adresse IP du serveur, doit correspondre à l'adresse indiquée dans default.yaml
    port : 4202 # Le port du serveur, doit correspondre au port indiqué dans default.yaml

# Paramètres capteur
sensor :
  exposure : 0.3 # Temps d'exposition (secondes) (float)
  max : 100
  min : 0

# Paramètres client
client :
  storage_path : ./depot # Chemin vers le dossier de depot, de préférence absolu

# Paramètres module
module :
  shots : ./shots
  delay : 300 # Delai entre deux captures (secondes) (int)