# --------------------------------------------------------------
# Ce fichier contient tous les paramètres par défaut du module.
# ! Ne pas modifier les noms de variables !
# Les valeurs peuvent être mdifiées selon les préférences.
# Les indentations doivent être respectées strictement.
# --------------------------------------------------------------

# Paramètres réseau
#Paramètres réseau local
network :
  server :
    host : 10.0.0.20 #L'adresse IP du module, doit correspondre à l'adresse indiquée dans default.yaml
    port : 4202 #Le port du serveur, doit correspondre au port indiqué dans default.yaml

#Paramètres client
client :
  depot : /depot/


#Paramètres module
module :
  shots : /shots/
  delay : 5 #Delai entre deux captures (secondes) (int)

  clock:
    time_interval : 2  #Synchroniser l'horloge toutes les (sync_interval) captures (int)
    conf_interval : 3 #Synchroniser la configuration toutes les (conf_interval) captures (int)

  #Paramètres capteur
  sensor :
    output_size : #Resolution brute des images capturées par le capteur
      width : #Largeur (pixels) (int)
      height : #Hauteur (pixels) (int)
    bit_depth : #Nombre de bits utilisés pour représenter la couleur de chaque pixel. Valeurs possibles: 10 ou 12 (bits) (int)

  #Paramètres nommage
  naming :
    image_name : StationFac_L1_ImageCiel_{timestamp}.jpg #Nom du fichier image avec timestamp
    timestamp : \%Y%m%d%H%M%S #Format du timestamp

  brightness_threshold : 10 #Seuil de luminosité pour refuser une capture (lux) (int)

  #Paramètres mode nuit
  night_mode : 
    enabled : true #Activer le mode nuit (bool)
    delay : #Delai entre deux captures la nuit (secondes) (int)
    start_hour : 20 #Heure de début du mode nuit (heures) (int)
    end_hour : 6 #Heure de fin du mode nuit (heures) (int)
