# --------------------------------------------------------------
# Ce fichier contient tous les paramètres par défaut du module.
# ! Ne pas modifier les noms de variables !
# Les valeurs peuvent être mdifiées selon les préférences.
# Les indentations doivent être respectées strictement.
# --------------------------------------------------------------

# Paramètres réseau
network :
  server :
    host : localhost # L'adresse IP du serveur, doit correspondre à l'adresse indiquée dans config.yaml
    port : 4202 # Le port du serveur, doit correspondre au port indiqué dans config.yaml

# Paramètres client
client :
  depot : /depot/


# Paramètres module
module :
  shots : /shots/
  delay : 300 # Delai entre deux captures (secondes) (int)

  clock:
    sync_interval: 60  # Synchroniser l'horloge toutes les (sync_interval) secondes (int)

  # Paramètres capteur
  sensor :
    output_size: #Resolution brute des images capturées par le capteur
      width: 
      height: 
    bit_depth: #Nombre de bits utilisés pour représenter la couleur de chaque pixel. Valeurs possibles: 10 ou 12 (bits)

  format :
    image_name : 'StationFac_L1_ImageCiel_{timestamp}.jpg'
    timestamp : '%Y%m%d%H%M%S'

  brightness_threshold :  #En Lux

  night_mode : 
    enabled : true #Activer le mode nuit
    delay : #Delai entre deux captures la nuit (secondes) (int)
    start_hour : 20 #En heures
    end_hour : 6 #En heures

